#!/bin/bash
# Bootstrap configuration.
#   $ git clone https://github.com/kwarrick/dotfiles config
#   $ ./config/bootstrap
cd ~
ln -s config/vimrc ~/.vimrc
ln -s config/vim ~/.vim
ln -s config/tmux.conf ~/.tmux.conf
mkdir ~/.vim/bundle
git clone https://github.com/gmarick/vundle ~/.vim/bundle/vundle

